name: Generate release-artifacts

# on events
on: workflow_dispatch

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: ''
          name: 'argodocs'
          compress: 'true'
          dest: 'dist'
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "argodocs-release-v${{ env.GITHUB_RUN_NUMBER }}"
          files: |
            ./dist/argodocs-linux-amd64
            ./dist/argodocs-darwin-amd64
            ./dist/argodocs-windows-amd64